source 'https://rubygems.org'
ruby '3.2.2'

gem 'sinatra', '>= 2.0.2'
gem 'sinatra-flash', '0.3.0'
gem "rack", "~> 2.2"

group :development, :test do
#  gem 'cucumber'
#  gem 'cucumber-sinatra'
#  gem 'capybara'

  gem 'rspec'


 gem 'rack-test'
  gem 'rack_session_access'

  gem 'byebug'
  gem 'launchy'
 gem 'rerun'

  gem 'simplecov'
  gem 'webmock'
end


gem "puma", "~> 6.6"
#
group :development do
  gem 'rerun'
end
